import type { Db } from "./db/index.js";
import { insertAuditLog } from "./repo.js";
export type AuditEventType="auth.signin"|"auth.signout"|"auth.failed"|"task.create"|"task.approve"|"task.deny"|"task.stop"|"task.complete"|"task.fail"|"grant.issue"|"grant.deny"|"grant.expire"|"grant.replay"|"approval.create"|"approval.use"|"approval.expire"|"approval.replay"|"capability.lease"|"capability.consume"|"capability.expire"|"governance.pass"|"governance.fail"|"governance.deny"|"kill_switch.engage"|"kill_switch.release"|"secret.rotate"|"backup.create"|"backup.verify"|"tool.invoke"|"tool.deny"|"tool.result"|"video.create"|"video.approve"|"video.deny"|"video.stop"|"workspace.create"|"workspace.update"|"user.create"|"user.update"|"user.role_change"|"admin.action"|"system.startup"|"system.readiness";
export interface AuditEvent{eventType:AuditEventType;actorId?:number|null;tenantId?:number|null;taskId?:number|null;resourceType?:string|null;resourceId?:string|null;outcome:"success"|"failure"|"denied";detail?:Record<string,unknown>|null;requestId?:string|null;ipAddress?:string|null;}
export async function audit(db:Db,event:AuditEvent,options:{required?:boolean}={}):Promise<void>{
 try{await insertAuditLog(db,{eventType:event.eventType,actorId:event.actorId??undefined,tenantId:event.tenantId??undefined,taskId:event.taskId??undefined,resourceType:event.resourceType??undefined,resourceId:event.resourceId??undefined,outcome:event.outcome,detail:event.detail??undefined,requestId:event.requestId??undefined,ipAddress:event.ipAddress??undefined});}
 catch(err){if(options.required)throw err;console.error("[audit] failed to write audit log:",err);}
}
export function getRequestId(req:{headers:Record<string,string|string[]|undefined>}):string{const v=req.headers["x-request-id"];return typeof v==="string"?v.slice(0,64):"";}
export function getIpAddress(req:{ip?:string;headers:Record<string,string|string[]|undefined>}):string{const v=req.headers["x-forwarded-for"];return typeof v==="string"?(v.split(",")[0]?.trim()??""):req.ip??"";}