import { sha256, canonicalize } from "./security.js";
import { verifyChain, chainEntry, type TrajectoryEntry } from "./merkle.js";
export type InvariantViolation={code:string;detail?:unknown};
export function assertNoViolations(v:InvariantViolation[]):void{if(v.length)throw new Error(`Invariant violations: ${v.map(x=>x.code).join(", ")}`);}
export function buildTrajectoryChain(steps:Array<{stepIndex:number;inputDigest:string;outputDigest:string|null}>):TrajectoryEntry[]{const sorted=[...steps].sort((a,b)=>a.stepIndex-b.stepIndex),chain:TrajectoryEntry[]=[];for(const step of sorted){const d=sha256(`${step.stepIndex}:${step.inputDigest}:${step.outputDigest??"null"}`);chain.push(chainEntry(step.stepIndex,d,chain.at(-1)??null));}return chain;}
export function verifyTrajectoryIntegrity(steps:Array<{stepIndex:number;inputDigest:string;outputDigest:string|null;chainHash:string;prevChainHash:string|null}>):boolean{
 const sorted=[...steps].sort((a,b)=>a.stepIndex-b.stepIndex),expected=buildTrajectoryChain(sorted);if(!verifyChain(expected)||expected.length!==sorted.length)return false;
 for(let i=0;i<sorted.length;i++){if(sorted[i]!.chainHash!==expected[i]!.chainHash)return false;const prev=i===0?"genesis":expected[i-1]!.chainHash;if((sorted[i]!.prevChainHash??"genesis")!==prev)return false;}return true;
}
export function computeTrajectoryRoot(steps:Array<{stepIndex:number;inputDigest:string;outputDigest:string|null}>):string{if(!steps.length)return sha256("empty-trajectory");return buildTrajectoryChain(steps).at(-1)!.chainHash;}
export function checkTaskInvariants(task:{id:number;status:string;tenantId:number;createdByUserId:number|null;budgetTokensUsed:number;budgetBytesUsed:number;trajectoryRootHash:string|null;trajectorySteps:number}){const v:InvariantViolation[]=[];if(!task.id||task.id<=0)v.push({code:"task_id_invalid"});if(!task.tenantId)v.push({code:"task_tenant_missing"});if(task.budgetTokensUsed<0)v.push({code:"budget_tokens_negative"});if(task.budgetBytesUsed<0)v.push({code:"budget_bytes_negative"});if(task.trajectorySteps>0&&!task.trajectoryRootHash)v.push({code:"trajectory_root_missing"});if(!["pending","running","waiting_approval","done","failed","cancelled"].includes(task.status))v.push({code:"task_status_invalid"});return v;}
export function checkStepInvariants(step:{id:number;taskId:number;stepIndex:number;agentRole:string;toolName:string;operation:string;inputDigest:string;outputDigest:string|null;chainHash:string;prevChainHash:string|null}){const v:InvariantViolation[]=[];if(!step.id||step.id<=0)v.push({code:"step_id_invalid"});if(!step.taskId||step.taskId<=0)v.push({code:"step_task_missing"});if(!Number.isInteger(step.stepIndex)||step.stepIndex<0)v.push({code:"step_index_invalid"});if(!step.agentRole)v.push({code:"step_agent_missing"});if(!step.toolName)v.push({code:"step_tool_missing"});if(!/^[0-9a-f]{64}$/.test(step.inputDigest))v.push({code:"step_input_digest_invalid"});if(step.outputDigest!==null&&!/^[0-9a-f]{64}$/.test(step.outputDigest))v.push({code:"step_output_digest_invalid"});if(!/^[0-9a-f]{64}$/.test(step.chainHash))v.push({code:"step_chain_hash_invalid"});return v;}
export function digestToolInput(tool:string,operation:string,params:Record<string,unknown>):string{return sha256(`tool-input:${tool}:${operation}:${canonicalize(params)}`);}
export function digestToolOutput(tool:string,operation:string,result:unknown):string{return sha256(`tool-output:${tool}:${operation}:${canonicalize(result)}`);}