import { createHash,createPrivateKey,createPublicKey,sign as cryptoSign,verify as cryptoVerify } from 'node:crypto';
import dns from 'node:dns/promises';import https from 'node:https';import net from 'node:net';
export function canonicalize(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(canonicalize).join(',')+']';const r=value as Record<string,unknown>;return '{'+Object.keys(r).sort().map(k=>JSON.stringify(k)+':'+canonicalize(r[k])).join(',')+'}';}
export function sha256(v:string|Buffer){return createHash('sha256').update(v).digest('hex');}
export function grantSigningPayload(g:Record<string,unknown>){const{signature:_sig,...frozen}=g;return canonicalize(frozen);}
export function signGrant(g:Record<string,unknown>,issuer:string,privateKeyPem:string){return{issuer,signature:cryptoSign(null,Buffer.from(grantSigningPayload({...g,issuer})),createPrivateKey(privateKeyPem)).toString('base64url')};}
export function verifyGrantSignature(g:Record<string,unknown>,issuer:string,signature:string,publicKeyPem:string){try{return cryptoVerify(null,Buffer.from(grantSigningPayload({...g,issuer})),createPublicKey(publicKeyPem),Buffer.from(signature,'base64url'));}catch{return false;}}
export function assertHttpsUrl(raw:string){const u=new URL(raw);if(u.protocol!=='https:')throw new Error('https_required');if(u.username||u.password)throw new Error('url_credentials_forbidden');return u;}
export function isPrivateOrLocalHost(hn:string){const h=hn.toLowerCase().replace(/^\[|\]$/g,'');if(h==='localhost'||h==='::1'||h==='0.0.0.0'||h.endsWith('.local')||h.endsWith('.internal')||h==='metadata.google.internal')return true;if(/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h)||/^172\.(1[6-9]|2[0-9]|3[01])\./.test(h)||/^127\./.test(h))return true;if(/^(fc|fd)[0-9a-f]{2}:/i.test(h)||/^fe8[0-9a-f]:/i.test(h)||/^fe9[0-9a-f]:/i.test(h)||/^fea[0-9a-f]:/i.test(h)||/^feb[0-9a-f]:/i.test(h))return true;return false;}
function isUnsafeResolvedAddress(address:string){const n=address.toLowerCase().replace(/^\[|\]$/g,'');if(net.isIPv4(n)){const p=n.split('.').map(Number),a=p[0]??-1,b=p[1]??-1,c=p[2]??-1;return a===0||a===10||a===127||(a===169&&b===254)||(a===192&&b===168)||(a===172&&b>=16&&b<=31)||(a===100&&b>=64&&b<=127)||(a===192&&b===0&&c===0)||(a===198&&(b===18||b===19))||a>=224;}if(net.isIPv6(n)){if(n==='::'||n==='::1'||n.startsWith('fc')||n.startsWith('fd')||n.startsWith('fe8')||n.startsWith('fe9')||n.startsWith('fea')||n.startsWith('feb')||n.startsWith('ff'))return true;const m=n.match(/^::ffff:(\d+\.\d+\.\d+\.\d+)$/);if(m?.[1])return isUnsafeResolvedAddress(m[1]);}return false;}
export async function governedFetch(raw:string,init:RequestInit={},maxResponseBytes=4*1024*1024){const u=assertHttpsUrl(raw);if(init.redirect&&init.redirect!=='manual')throw new Error('redirects_must_be_manual');const allowed=(init as RequestInit&{__allowedHosts?:readonly string[]}).__allowedHosts;if(allowed)assertEgressUrl(raw,allowed);const resolved=await dns.lookup(u.hostname,{all:true,verbatim:true});if(!resolved.length||resolved.some(x=>isUnsafeResolvedAddress(x.address)))throw new Error('unsafe_dns_destination');const target=resolved[0]?.address;if(!target)throw new Error('dns_no_destination');const method=String(init.method??'GET').toUpperCase();const headers=new Headers(init.headers);headers.set('host',u.host);const body=typeof init.body==='string'?Buffer.from(init.body):Buffer.isBuffer(init.body)?init.body:init.body?Buffer.from(init.body as ArrayBuffer):undefined;if(body&&!headers.has('content-length'))headers.set('content-length',String(body.byteLength));return await new Promise<Response>((resolve,reject)=>{const req=https.request({hostname:target,port:Number(u.port||443),path:u.pathname+u.search,method,headers:Object.fromEntries(headers.entries()),servername:net.isIP(u.hostname)?undefined:u.hostname,rejectUnauthorized:true,signal:init.signal??undefined},response=>{const chunks:Buffer[]=[];let total=0;response.on('data',chunk=>{const b=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);total+=b.byteLength;if(total>maxResponseBytes){req.destroy(new Error('response_too_large'));return;}chunks.push(b);});response.on('end',()=>{const buf=Buffer.concat(chunks),rh=new Headers();for(const[key,value]of Object.entries(response.headers)){if(Array.isArray(value)){for(const v of value)rh.append(key,v);}else if(value!==undefined)rh.set(key,String(value));}resolve(new Response(buf,{status:response.statusCode??0,statusText:response.statusMessage??'',headers:rh}));});response.on('error',reject);});req.on('error',reject);if(body)req.write(body);req.end();});}
export function assertEgressUrl(raw:string,allowedHosts:readonly string[]){const u=assertHttpsUrl(raw);if(isPrivateOrLocalHost(u.hostname))throw new Error('private_destination_blocked');const host=u.hostname.toLowerCase();if(!allowedHosts.some(rule=>rule===host||(rule.startsWith('*.')&&host.endsWith(rule.slice(1)))))throw new Error('egress_destination_not_allowlisted');return u;}