import type { FastifyPluginAsync } from "fastify";
import { z } from "zod";
import { resolveSession } from "./auth.js";
import { findUserById,listPendingApprovals,findApprovalById,reviewApproval,insertAuditLog } from "../repo.js";
import type { Db } from "../db/index.js";
declare module "fastify"{interface FastifyInstance{db:Db;}}
const reviewSchema=z.object({status:z.enum(["approved","denied"]),reason:z.string().max(1000).optional()});
export const approvalRoutes:FastifyPluginAsync=async app=>{
 app.get("/",async(req,reply)=>{const s=await resolveSession(app.db,req.cookies as Record<string,string>);if(!s)return reply.status(401).send({error:"Unauthenticated",code:"unauthenticated"});return reply.send(await listPendingApprovals(app.db,s.tenantId));});
 app.patch("/:id",async(req,reply)=>{const s=await resolveSession(app.db,req.cookies as Record<string,string>);if(!s)return reply.status(401).send({error:"Unauthenticated",code:"unauthenticated"});const u=await findUserById(app.db,s.userId,s.tenantId);if(!u)return reply.status(401).send({error:"Unauthenticated"});if(!["owner","admin"].includes(u.role))return reply.status(403).send({error:"Only owner/admin can review approvals.",code:"forbidden"});const id=Number((req.params as {id:string}).id);if(!Number.isInteger(id))return reply.status(400).send({error:"Invalid approval ID"});const p=reviewSchema.safeParse(req.body);if(!p.success)return reply.status(400).send({error:"Invalid input"});const current=await findApprovalById(app.db,id,s.tenantId);if(!current)return reply.status(404).send({error:"Approval not found"});if(current.status!=="pending")return reply.status(409).send({error:`Approval already ${current.status}.`});if(current.expiresAt<=new Date())return reply.status(410).send({error:"Approval request has expired.",code:"expired"});const updated=await reviewApproval(app.db,id,s.tenantId,s.userId,p.data.status,p.data.reason);if(!updated)return reply.status(409).send({error:"Approval was already reviewed by another request.",code:"approval_race"});await insertAuditLog(app.db,{eventType:`approval.${p.data.status}`,actorId:s.userId,tenantId:s.tenantId,taskId:current.taskId??undefined,resourceType:"approval",resourceId:String(id),outcome:"success",detail:{reason:p.data.reason},ipAddress:req.ip});return reply.send({ok:true,approval:updated});});
};