import type { FastifyPluginAsync } from "fastify";
import { z } from "zod";
import bcrypt from "bcryptjs";
import { randomBytes,createHash } from "node:crypto";
import { findTenantBySlug,findUserByEmail,registerDefaultUserAtomic,createSession,findSessionByTokenHash,deleteSession,insertAuditLog } from "../repo.js";
import type { Db } from "../db/index.js";
declare module "fastify"{interface FastifyInstance{db:Db;}}
const SESSION_TTL_MS=7*24*60*60*1000,SALT_ROUNDS=12,DEFAULT_TENANT_SLUG="default",ALLOW_SELF_REGISTRATION=process.env.ALLOW_SELF_REGISTRATION==="true";
const hashToken=(t:string)=>createHash("sha256").update(t).digest("hex");
const loginSchema=z.object({email:z.string().email(),password:z.string().min(1)}),registerSchema=z.object({email:z.string().email(),password:z.string().min(12)});
function setCookieToken(reply:unknown,token:string){(reply as {setCookie:(n:string,v:string,o:unknown)=>void}).setCookie("session",token,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",path:"/",maxAge:SESSION_TTL_MS/1000});}
export const authRoutes:FastifyPluginAsync=async app=>{
 app.get("/bootstrap",async(_req,reply)=>reply.send({bootstrap:false,allowSelfRegistration:ALLOW_SELF_REGISTRATION}));
 app.post("/register",async(req,reply)=>{const p=registerSchema.safeParse(req.body);if(!p.success)return reply.status(400).send({error:"Invalid input",code:"invalid_input"});const passwordHash=await bcrypt.hash(p.data.password,SALT_ROUNDS),token=randomBytes(32).toString("hex");try{const r=await registerDefaultUserAtomic(app.db,{tenantSlug:DEFAULT_TENANT_SLUG,email:p.data.email,passwordHash,tokenHash:hashToken(token),expiresAt:new Date(Date.now()+SESSION_TTL_MS),allowSelfRegistration:ALLOW_SELF_REGISTRATION,maxUsers:50});setCookieToken(reply,token);await insertAuditLog(app.db,{eventType:"user.create",actorId:r.user.id,tenantId:r.tenant.id,outcome:"success",ipAddress:req.ip});return reply.status(201).send({ok:true});}catch(e){const code=e instanceof Error?e.message:"registration_failed";const map:Record<string,{status:number;code:string}>={registration_closed:{status:403,code:"registration_closed"},limit_reached:{status:403,code:"limit_reached"},email_taken:{status:409,code:"email_taken"}};const m=map[code]??{status:409,code:"registration_failed"};return reply.status(m.status).send({error:code,code:m.code});}});
 app.post("/login",async(req,reply)=>{const p=loginSchema.safeParse(req.body);if(!p.success)return reply.status(400).send({error:"Invalid input",code:"invalid_input"});const tenant=await findTenantBySlug(app.db,DEFAULT_TENANT_SLUG);if(!tenant)return reply.status(401).send({error:"Invalid credentials.",code:"invalid_credentials"});const user=await findUserByEmail(app.db,tenant.id,p.data.email);if(!user){await bcrypt.hash(p.data.password,SALT_ROUNDS);return reply.status(401).send({error:"Invalid credentials.",code:"invalid_credentials"});}if(!(await bcrypt.compare(p.data.password,user.passwordHash)))return reply.status(401).send({error:"Invalid credentials.",code:"invalid_credentials"});const token=randomBytes(32).toString("hex");await createSession(app.db,user.id,tenant.id,hashToken(token),new Date(Date.now()+SESSION_TTL_MS));setCookieToken(reply,token);return reply.send({ok:true});});
 app.post("/logout",async(req,reply)=>{const token=(req.cookies as Record<string,string>)["session"];if(token){const s=await findSessionByTokenHash(app.db,hashToken(token));if(s){await deleteSession(app.db,s.id);await insertAuditLog(app.db,{eventType:"auth.signout",actorId:s.userId,tenantId:s.tenantId,outcome:"success",ipAddress:req.ip});}}reply.clearCookie("session",{path:"/"});return reply.send({ok:true});});
};
export async function resolveSession(db:Db,cookies:Record<string,string>){const token=cookies["session"];if(!token)return null;const s=await findSessionByTokenHash(db,hashToken(token));if(!s)return null;if(s.expiresAt<new Date()){await deleteSession(db,s.id);return null;}return s;}