import type { FastifyPluginAsync } from "fastify";
import { z } from "zod";
import { resolveSession } from "./auth.js";
import { findUserById,createTask,findTaskById,listTasksByTenant,updateTaskStatus,listTaskSteps,insertAuditLog } from "../repo.js";
import type { Db } from "../db/index.js";
declare module "fastify"{interface FastifyInstance{db:Db;}}
const createSchema=z.object({title:z.string().min(1).max(500),description:z.string().max(5000).optional(),classification:z.enum(["standard","sensitive","restricted"]).optional(),budgetTokensAllocated:z.number().int().min(100).max(500000).optional(),budgetBytesAllocated:z.number().int().min(1024).max(104857600).optional()});
const canAct=(role:string)=>["owner","admin","operator"].includes(role);
export const taskRoutes:FastifyPluginAsync=async app=>{
 app.get("/",async(req,reply)=>{const s=await resolveSession(app.db,req.cookies as Record<string,string>);if(!s)return reply.status(401).send({error:"Unauthenticated",code:"unauthenticated"});return reply.send(await listTasksByTenant(app.db,s.tenantId));});
 app.get("/:id",async(req,reply)=>{const s=await resolveSession(app.db,req.cookies as Record<string,string>);if(!s)return reply.status(401).send({error:"Unauthenticated",code:"unauthenticated"});const id=Number((req.params as {id:string}).id);if(!Number.isInteger(id))return reply.status(400).send({error:"Invalid task ID"});const task=await findTaskById(app.db,id,s.tenantId);if(!task)return reply.status(404).send({error:"Task not found"});return reply.send({...task,steps:await listTaskSteps(app.db,id,s.tenantId)});});
 app.post("/",async(req,reply)=>{const s=await resolveSession(app.db,req.cookies as Record<string,string>);if(!s)return reply.status(401).send({error:"Unauthenticated",code:"unauthenticated"});const u=await findUserById(app.db,s.userId,s.tenantId);if(!u)return reply.status(401).send({error:"Unauthenticated"});if(!canAct(u.role))return reply.status(403).send({error:"Insufficient role to create tasks.",code:"forbidden"});const p=createSchema.safeParse(req.body);if(!p.success)return reply.status(400).send({error:"Invalid input",details:p.error.issues});const task=await createTask(app.db,{tenantId:s.tenantId,createdByUserId:s.userId,...p.data});await insertAuditLog(app.db,{eventType:"task.create",actorId:s.userId,tenantId:s.tenantId,taskId:task.id,resourceType:"task",resourceId:String(task.id),outcome:"success",ipAddress:req.ip});return reply.status(201).send(task);});
 app.post("/:id/cancel",async(req,reply)=>{const s=await resolveSession(app.db,req.cookies as Record<string,string>);if(!s)return reply.status(401).send({error:"Unauthenticated",code:"unauthenticated"});const u=await findUserById(app.db,s.userId,s.tenantId);if(!u)return reply.status(401).send({error:"Unauthenticated"});if(!canAct(u.role))return reply.status(403).send({error:"Insufficient role to cancel tasks.",code:"forbidden"});const id=Number((req.params as {id:string}).id);if(!Number.isInteger(id))return reply.status(400).send({error:"Invalid task ID"});const t=await findTaskById(app.db,id,s.tenantId);if(!t)return reply.status(404).send({error:"Task not found"});if(["done","failed","cancelled"].includes(t.status))return reply.status(409).send({error:`Task is already ${t.status}.`});await updateTaskStatus(app.db,id,s.tenantId,"cancelled");await insertAuditLog(app.db,{eventType:"task.stop",actorId:s.userId,tenantId:s.tenantId,taskId:id,outcome:"success",ipAddress:req.ip});return reply.send({ok:true});});
};